Do not show select payment frequency after login as frequency is already selected
Exception: Account details upgrade view where frequency needs to be selected